### ISSUE TITLE
Filter by `visible` and `active`

### ISSUE THREAD

**Issue by cassidyjames** [AKiniyalocts/superfan-v2#1]
Right now the app is showing all products, whether `active: true` and `visible: true` or not. 

* `active` is whether or not the product is able to be purchased
* `visible` is whether or not the product should appear on the site, in an app, etc.

A product may be `visible` but not `active`, for example, if it is temporarily sold out. A product may be `active` but not `visible`, for example, if it is purchasable from the back-end but not intended to be shown to customers.

**Comment by AKiniyalocts** [comment]
Ah I was only filtering for `active`. Thanks for the report Cassidy!
